0:
  - !ruby/range 1..250: 
      z_value: 0.75
      turning_moment: &turning_moment 8
      forward_pressure: &forward_pressure 29 
  - !ruby/range 251..270: 
      z_value: 0.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
1:
  - !ruby/range 1..250: 
      z_value: 1
      turning_moment: &turning_moment 11
      forward_pressure: &forward_pressure 40 
  - !ruby/range 251..270: 
      z_value: 1
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 0.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
2:
  - !ruby/range 1..250: 
      z_value: 1.5
      turning_moment: &turning_moment 14
      forward_pressure: &forward_pressure 52
  - !ruby/range 251..270: 
      z_value: 1.25
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 1
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure   
3:
  - !ruby/range 1..250: 
      z_value: 1.75
      turning_moment: &turning_moment 17
      forward_pressure: &forward_pressure 64
  - !ruby/range 251..270: 
      z_value: 1.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 1.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 1.25
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
4:
  - !ruby/range 1..250: 
      z_value: 2.25
      turning_moment: &turning_moment 20
      forward_pressure: &forward_pressure 75
  - !ruby/range 251..270: 
      z_value: 2
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 1.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 1.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 1.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
5:
  - !ruby/range 1..250: 
      z_value: 2.75
      turning_moment: &turning_moment 23
      forward_pressure: &forward_pressure 87
  - !ruby/range 251..270: 
      z_value: 2.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 2.25
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 2
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 1.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 1.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
6:
  - !ruby/range 1..250: 
      z_value: 3.5
      turning_moment: &turning_moment 27
      forward_pressure: &forward_pressure 102
  - !ruby/range 251..270: 
      z_value: 3
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 2.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 2.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 2.25
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 2
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
7:
  - !ruby/range 1..250: 
      z_value: ~ #of course dear yaml nil is ~ ;-)
      turning_moment: &turning_moment 31
      forward_pressure: &forward_pressure 120
  - !ruby/range 251..270: 
      z_value: 3.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 3
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 3
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 2.75
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 2.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
8:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 37
      forward_pressure: &forward_pressure 141
  - !ruby/range 251..270: 
      z_value: 4.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 4
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 3.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 3.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 3
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
9:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 43
      forward_pressure: &forward_pressure 165
  - !ruby/range 251..270: 
      z_value: 5.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 4.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 4
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 3.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
10:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 50
      forward_pressure: &forward_pressure 194
  - !ruby/range 251..270: 
      z_value: 6.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 6
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 5.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 4.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
11:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 58
      forward_pressure: &forward_pressure 229
  - !ruby/range 251..270: 
      z_value: 7.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 7
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 6.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 6
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 5.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
12:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 67
      forward_pressure: &forward_pressure 271
  - !ruby/range 251..270: 
      z_value: ~
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 8.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 8
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 7
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 6.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
13:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 78
      forward_pressure: &forward_pressure 320
  - !ruby/range 251..270: 
      z_value: ~
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 10
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 9.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 8.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 8
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
14:
  - !ruby/range 1..250: 
      z_value: ~ 
      turning_moment: &turning_moment 91
      forward_pressure: &forward_pressure 380
  - !ruby/range 251..270: 
      z_value: ~
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 271..290: 
      z_value: 11.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 291..310: 
      z_value: 11
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - !ruby/range 311..330: 
      z_value: 10
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
  - ? !ruby/range
        begin: 331
        end: .inf
    :
      z_value: 9.5
      turning_moment: *turning_moment
      forward_pressure: *forward_pressure
